on:
    pull_request:
        branches: [main]
    pull_request_review:
        types: [submitted, edited, dismissed]
    pull_request_review_comment:
        types: [created, edited, deleted]

permissions:
    contents: read
    pull-requests: write

jobs:
    test-action:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7

            - uses: ./
              with:
                  code-reviewed-color: "#ff0000"
                  code-reviewed-enabled: false
                  code-reviewed-label: "c reviewed"
                  copilot-logins: |
                      gh-copilot[bot]
                  copilot-ready-color: "#ff0000"
                  copilot-ready-enabled: false
                  copilot-ready-label: "c ready"
                  labels: |
                      {
                          "src/.*\\.ts": {
                              "name": "src",
                              "color": "#ff0000"
                          },
                          "src/.*\\.test\\.ts": {
                              "name": "test",
                              "color": "#00ff00"
                          }
                      }
                  pr-description-copilot-section-after: "## Copilot end"
                  pr-description-copilot-section-before: "## Copilot start"
                  pr-description-update-enabled: false
                  reviewer-usernames: |
                      frankfe-amsterdam
                      RikSchefferAmsterdam
                      WouterAms
                      fhaver-amsterdam
                      jjbeekman
