on:
    pull_request:
        branches: [main]
    pull_request_review:
        types: [submitted, edited, dismissed]
    pull_request_review_comment:
        types: [created, edited, deleted]

permissions:
    contents: read
    pull-requests: write

jobs:
    test-action:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7

            - uses: ./
              with:
                  reviewer-usernames: |
                      frankfe-amsterdam
                      RikSchefferAmsterdam
                      WouterAms
                      fhaver-amsterdam
                      jjbeekman
